#!/usr/bin/env bash
#Script that configures  Ubuntu machine to Perform  301-redirection

sudo apt-get -y update
sudo apt-get install -y nginx
sudo systemctl start nginx

# Creating an index.html 
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo systemctl reload nginx

# Using sed to do  301 Redirection
if ! grep -q "location /redirect_me {" /etc/nginx/sites-enabled/default; then
    sudo sed -i '/server_name _;/a'\
            'location /redirect_me {\
                return 301 https://github.com/Kakazablone;\
            }' /etc/nginx/sites-enabled/default
    # Reload Nginx service
    sudo systemctl reload nginx
fi
