#!/usr/bin/env bash
#script that displays Best School 10 times and Hi on the 9th 

idx=1

while [ $idx -le 20 ]
do
echo "$idx"
case $idx in
4) echo "bad luck from China";;
9) echo "bad luck from Japan";;
17) echo "bad luck from Italy";;
esac
(( idx++ ))
done
